In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_col= pd.read_csv("ColombiaCB.csv")
df_col["Country"] = "Colombia"
df_chi= pd.read_csv("ChileCB.csv")
df_chi["Country"] = "Chile"
df_bra= pd.read_csv("BrazilCB.csv")
df_bra["Country"] = "Brazil"
df_arg= pd.read_csv("ArgentinaCB.csv")
df_arg["Country"] = "Argentina"
df_mex= pd.read_csv("MexicoCB.csv")
df_mex["Country"] = "Mexico"
df_uru= pd.read_csv("UruguayCB.csv")
df_uru["Country"] = "Uruguay"

df_esp= pd.read_csv("SpainCB.csv")
df_esp["Country"] = "Spain"
df_sui= pd.read_csv("SwitzerlandCB.csv")
df_sui["Country"] = "Switzerland"
df_isr= pd.read_csv("IsraelCB.csv")
df_isr["Country"] = "Israel"
df_usa= pd.read_csv("UsaCB.csv")
df_usa["Country"] = "Usa"

In [4]:
df_all = pd.concat([df_col,df_chi,df_bra,df_arg, df_mex,df_uru, df_esp,df_sui, df_isr , df_usa] )
df_all = df_all.drop(["Organization Name URL"], axis=1)

In [5]:
df_all["Founded Date"] = pd.to_datetime(df_all["Founded Date"])
df_all["Exit Date"] = pd.to_datetime(df_all["Exit Date"])
df_all["Closed Date"] = pd.to_datetime(df_all["Closed Date"])
df_all["Last Funding Date"] = pd.to_datetime(df_all["Last Funding Date"])
df_all["Delisted Date"] = pd.to_datetime(df_all["Delisted Date"])
df_all["IPO Date"] = pd.to_datetime(df_all["IPO Date"])

In [21]:
df_startup = pd.read_excel("100startupcol.xlsx", index_col= 0)
df_startup =df_startup.rename(columns = {"1Doc3":"Startup"})
df_startup

       Startup        jcardona@1doc3.com
1
2         ADDI          ssuarez@addi.com
3       Aflore          manuel@aflore.co
4       Agrapp           david@agrapp.co
5       Aptuno      alejandro@aptuno.com
6       Arukay  vicky.ricaurte@gmail.com
..         ...                       ...
107  Monolegal                       NaN
108  Finsocial     santiago@finsocial.co
109        NaN                       NaN
110        NaN                       NaN
111        NaN                       NaN

[110 rows x 2 columns]

In [12]:
# intentemos con un merge

df_col_top_100 = pd.merge(df_col, df_startup, left_on="Organization Name", right_on= "Startup"  )
df_col_top_100 = df_col_top_100["Organization Name"].astype(str) 
df_col_top_100

0                La Haus
1                 Aflore
2                 Liftit
3                 Chiper
4                   Habi
5                  Valiu
6                  Rappi
7                 Zinobe
8     Mensajeros Urbanos
9              Finsocial
10                  Vozy
11                  Leal
12                Avista
13                Truora
14             Finaktiva
15                Sempli
16            Lentesplus
17                  Bold
18             Mi Aguila
19                 Foody
20            Farmalisto
21                 Minka
22              Simetrik
23             Foodology
24                 Peiky
25               Tributi
26                Aptuno
27                CIVICO
28               Frubana
29                Fitpal
30                  Loro
31              Valienta
32            Saludtools
33              Hometuls
34                Licify
35                Mowies
36                 Movii
37            Symplifica
38         LaManicurista
39               Talentu
40                Agrapp
41                Arukay
42                 Pulzo
43              Direktio
44               Mobijob
45             Monolegal
Name: Organization Name, dtype: object

In [30]:
print("Data Total Filas: %f"%(df_all.shape[1]))
print("Data TotalColumnas: %d"%(df_all.shape[0]))

print("100 Startup Filas: %d"%(df_startup.shape[1]))
print("100 Startup Columnas: %d"%(df_startup.shape[0]))

Data Total Filas: 103.000000
Data TotalColumnas: 9259
100 Startup Filas: 2
100 Startup Columnas: 110

In [34]:
startup_contained = []
startup_not_contained = []

df_colombia_company = df_all[ df_all['Country'] == 'Colombia' ]
list_colombia_company_names = df_colombia_company['Organization Name'].tolist()

for i in range(100):
    top_company_name = df_startup.iloc[i].Startup
    if top_company_name.upper() in (top_company_name.upper() for top_company_name in list_colombia_company_names):
        startup_contained.append(top_company_name)
    else:
        startup_not_contained.append(top_company_name)

print("[%d] estan contenidas, [%d] no estan contenidas"%(len(startup_contained),len(startup_not_contained)))

[56] estan contenidas, [44] no estan contenidas

In [38]:
# lo mismo que tuvimos con el merge 
startup_contained

['ADDI',
 'Aflore',
 'Agrapp',
 'Aptuno',
 'Arukay',
 'Avista',
 'Biocredit',
 'Bold',
 'Chiper',
 'DataWifi',
 'Direktio',
 'EnLaU',
 'Farmalisto',
 'Finaktiva',
 'Fitpal',
 'Fluvip',
 'Foodology',
 'Foody',
 'Frubana',
 'Habi',
 'Hometuls',
 'La Haus',
 'Laika',
 'LaManicurista',
 'Leal',
 'Lentesplus',
 'Licify',
 'Liftit',
 'Loro',
 'Mensajeros Urbanos',
 'Mesfix',
 'Mi Aguila',
 'Minka',
 'Mobijob',
 'Movii',
 'Mowies',
 'Muncher',
 'Muvo',
 'Peiky',
 'Pulzo',
 'Queo',
 'Rappi',
 'Saludtools',
 'Sempli',
 'Simetrik',
 'Symplifica',
 'Talentu',
 'Tiendapp',
 'TPaga',
 'Tributi',
 'Truora',
 'Ubits',
 'Valienta',
 'Valiu',
 'Vozy',
 'Zinobe']

# ADICIONO CAMPO A DR_ALL

In [39]:
df_colombia_company["isInTop100"] = 0

pass

<ipython-input-39-e063b199bc96>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_colombia_company["isInTop100"] = 0

In [40]:
for company_name in startup_contained:
    df_colombia_company.loc[df_colombia_company['Organization Name'] == company_name, ['isInTop100']] = 1

C:\Users\Julian\anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [47]:
df_col_top100= df_colombia_company
df_col_top100[df_col_top100["isInTop100"]==1]

,Organization Name,Industries,Headquarters Location,Description,CB Rank (Company),Headquarters Regions,Estimated Revenue Range,Operating Status,Founded Date,Founded Date Precision,...,IPqwery - Patents Granted,IPqwery - Trademarks Registered,IPqwery - Most Popular Patent Class,IPqwery - Most Popular Trademark Class,Aberdeen - IT Spend,Aberdeen - IT Spend Currency,Aberdeen - IT Spend Currency (in USD),School Method,Country,isInTop100
0,La Haus,"Information Technology, Marketplace, Real Esta...","Medellín, Antioquia, Colombia",La Haus is a residential marketplace used to h...,"1,457",Latin America,$1M to $10M,Active,2017-04-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
4,Aflore,"Credit, Finance, Financial Services, FinTech","Bogotá, Distrito Especial, Colombia",Aflore is a developer of tech-enabled direct s...,"3,449",Latin America,$1M to $10M,Active,2012-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
7,Liftit,"Freight Service, Internet, Last Mile Transport...","Bogotá, Distrito Especial, Colombia",Liftit is the leading technology platform to a...,"5,562",Latin America,Less than $1M,Active,2017-01-07,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
8,Chiper,"B2B, E-Commerce, Retail Technology","Cundinamarca, Distrito Especial, Colombia",Chiper is a Colombian e-commerce platform for ...,"6,199",Latin America,$50M to $100M,Active,2018-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
9,Habi,"Home Renovation, Real Estate, Real Estate Inve...","Bogotá, Distrito Especial, Colombia",Habi is a digital platform that aims to simpli...,"7,387",Latin America,$1M to $10M,Active,2019-07-01,month,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
10,Valiu,"Cryptocurrency, Finance, Financial Services, F...","Bogotá, Distrito Especial, Colombia",Valiu is a developing a digital remittance pla...,"7,499",Latin America,$1M to $10M,Active,2018-09-17,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
11,Rappi,"Consumer Goods, E-Commerce, Food Delivery","Bogotá, Distrito Especial, Colombia",Rappi is a consumer tech company that speciali...,"7,739",Latin America,$10M to $50M,Active,2015-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
13,Zinobe,"Big Data, Credit, Financial Services, FinTech,...","Bogotá, Distrito Especial, Colombia",Digital financial services company in the Colo...,"9,826",Latin America,$1M to $10M,Active,2011-07-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
15,Mensajeros Urbanos,NaN,"Bogotá, Distrito Especial, Colombia",The largest and diverse collaborative logistic...,"10,312",Latin America,$1M to $10M,Active,2013-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
19,Vozy,"Artificial Intelligence, Enterprise Software, ...","Medellín, Antioquia, Colombia",Vozy is a voice AI platform that helps compani...,"12,160",Latin America,Less than $1M,Active,2016-01-18,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
20,Leal,"Analytics, Information Services, Information T...","Bogotá, Distrito Especial, Colombia",Leal is a digital platform for retailers in La...,"12,766",Latin America,$1M to $10M,Active,2016-06-15,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
25,Avista,"Financial Services, FinTech","Bogotá, Distrito Especial, Colombia",Avista is a technology-based financial company...,"13,927",Latin America,$1B to $10B,Active,2019-02-01,month,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
26,Truora,"Developer Platform, Information Services, Secu...","Cali, Valle del Cauca, Colombia","Truora provides fast, innovative, and safe sol...","14,245",Latin America,$1M to $10M,Active,2018-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
29,Finaktiva,"Financial Services, FinTech, Information Techn...","Medellín, Antioquia, Colombia",Online lending platform for high impact SMEs i...,"14,873",Latin America,Less than $1M,Active,2017-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
31,Sempli,"Financial Services, FinTech, Lending, Online P...","Medellín, Antioquia, Colombia",Sempli is the leading online lending platform ...,"16,658",Latin America,Less than $1M,Active,2017-01-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
34,Lentesplus,"Customer Service, E-Commerce, Eyewear, Health ...","Bogotá, Distrito Especial, Colombia",Lentesplus.com is the leading online contact l...,"17,846",Latin America,$1M to $10M,Active,2014-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
35,Bold,"Credit Cards, Debit Cards, Financial Services,...","Bogotá, Distrito Especial, Colombia",Offers financial services to SMBs in Colombia,"18,050",Latin America,$1M to $10M,Active,2019-05-06,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
36,Mi Aguila,"E-Commerce, Logistics, Software","Bogotá, Distrito Especial, Colombia",Mi Aguila is a technology company focused on e...,"18,626",Latin America,$1M to $10M,Active,2015-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
37,Foody,"E-Commerce, Food and Beverage, Mobile Apps","Bogotá, Distrito Especial, Colombia",Foody provides healthy food to the vast majori...,"19,798",Latin America,Less than $1M,Active,2017-01-06,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
39,Farmalisto,"E-Commerce, Health Care","Bogotá, Distrito Especial, Colombia",First regional pure player Online Pharmacy and...,"20,112",Latin America,NaN,Active,2013-10-17,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
42,Minka,"Blockchain, Financial Services, FinTech, Ventu...","Bogotá, Distrito Especial, Colombia",Minka is a financial services cloud that enabl...,"20,530",Latin America,Less than $1M,Active,2015-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
45,Simetrik,"Financial Services, FinTech, Software","Bogotá, Distrito Especial, Colombia",Simetrik is a fintech startup delivering finan...,"23,000",Latin America,$1M to $10M,Active,2017-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
47,Foodology,"Delivery, Food and Beverage, Food Delivery, Re...","Bogotá, Distrito Especial, Colombia",Foodology creates and operates digital restaur...,"24,300",Latin America,NaN,Active,2019-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
50,Peiky,"E-Commerce, E-Commerce Platforms, Mobile, Soci...","Bogotá, Distrito Especial, Colombia",A solution (web & mobile) that empowers the so...,"27,817",Latin America,$10M to $50M,Active,2018-06-26,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
51,Tributi,"Finance, Financial Services, FinTech, Service ...","Medellín, Antioquia, Colombia",Tributi is a Colombian fintech start-up backed...,"27,840",Latin America,Less than $1M,Active,2018-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
52,Aptuno,"Property Management, Real Estate","Bogotá, Distrito Especial, Colombia",Aptuno is a platform that provides seamless se...,"27,856",Latin America,NaN,Active,2019-09-01,month,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
61,Frubana,"AgTech, B2B, E-Commerce, Logistics, Restaurants","Bogotá, Distrito Especial, Colombia",Frubana is a B2B platform of agri-products and...,"32,289",Latin America,$1M to $10M,Active,2018-06-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
67,Fitpal,"Fitness, Training, Wellness","Bogotá, Distrito Especial, Colombia",Fitpal is a monthly membership that gives you ...,"34,928",Latin America,Less than $1M,Active,2015-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
80,Loro,"E-Commerce, Mobile Apps, Retail, Shopping Mall...","Bogotá, Distrito Especial, Colombia",Loro transforms “brick-and-mortar” shopping ma...,"44,432",Latin America,NaN,Active,2017-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
82,Valienta,"E-Commerce, E-Commerce Platforms, Marketplace,...","Medellín, Antioquia, Colombia",Valienta is a marketplace that enables social ...,"46,283",Latin America,Less than $1M,Active,2020-01-06,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
94,Saludtools,"Electronic Health Record (EHR), Health Care, M...","Bogotá, Distrito Especial, Colombia",We are about enabling better living conditions...,"51,849",Latin America,NaN,Active,2014-09-14,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
96,Hometuls,NaN,"Bogotá, Distrito Especial, Colombia",Hometuls connects suppliers with construction ...,"52,459",Latin America,NaN,Active,2019-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
99,Licify,"Construction, Procurement, SaaS","Bogotá, Distrito Especial, Colombia",Specialized procurment management platform tha...,"54,430",Latin America,$1M to $10M,Active,2017-09-01,month,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
233,Mowies,Media and Entertainment,"Medellín, Antioquia, Colombia",Mowies is a social platform where both video c...,"144,876",Latin America,NaN,Active,2016-07-26,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
245,Movii,Financial Services,"Bogotá, Distrito Especial, Colombia",Movii aims to reduce inequality by providing a...,"154,885",Latin America,NaN,Active,2017-01-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
247,Symplifica,"Employment, Financial Services, Service Indust...","Bogotá, Distrito Especial, Colombia",Symplifica is the payroll department of small ...,"155,667",Latin America,$1M to $10M,Active,2015-11-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
251,LaManicurista,"CRM, Information Technology, Internet, Logisti...","Cali, Valle del Cauca, Colombia",LaManicurista is an on-demand beauty marketpla...,"157,723",Latin America,NaN,Active,2016-10-15,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
257,Talentu,"Artificial Intelligence, Employment, Human Res...","Medellín, Antioquia, Colombia",Talentu is a hiring software startup that help...,"162,130",Latin America,NaN,Active,2018-08-16,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
266,Agrapp,"Agriculture, Farming, Financial Services, FinTech","Bogotá, Distrito Especial, Colombia",Agrapp is a financing platform that aims to st...,"166,836",Latin America,NaN,Active,2018-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
275,Arukay,"EdTech, Education","Bogotá, Distrito Especial, Colombia",ARUKAY is an educational company that provides...,"174,550",Latin America,$1M to $10M,Active,2014-07-24,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
297,Pulzo,"News, Publishing","Bogotá, Distrito Especial, Colombia",News Aggregator,"189,541",Latin America,NaN,Active,2013-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
608,Direktio,"Analytics, Big Data, Health Care","Bogotá, Distrito Especial, Colombia",Big Data - Advanced analytics in health,"428,527",Latin America,Less than $1M,Active,2013-10-01,day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1
664,Mobijob,"Apps, Market Research, Mobile Apps","Manizales, Caldas, Colombia",Mobijob is a mobile app that allows brands to ...,"461,201",Latin America,NaN,Active,2016-01-01,year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colombia,1